#
# lock-closed.yml
# Lock closed issues after a period of inactivity
#

name: 'Lock threads'

on:
  schedule:
    - cron: '59 * * * *'

jobs:
  lock:
    name: Lock Closed Issues
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: OSDKDev/lock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
