#
# lock-closed.yml
# Lock closed issues after a period of inactivity
#

name: "Lock closed issue"

on:
  schedule:
    - cron: '59 * * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
    - uses: OSDKDev/lock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
