#
# lock-closed.yml
# Lock closed issues after a period of inactivity
#

name: 'Lock threads'

on:
  schedule:
    - cron: '* */12 * * *'

jobs:
  lock:
    name: Lock Closed Issues
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: dessant/lock-threads@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
